export const ActionType = {
  // SET_CONTINUE_READING: 'SET_CONTINUE_READING',
  // SET_READ: 'SET_READ',
  // SET_WANT_TO_READ: 'SET_WANT_TO_READ',
  // SET_NONE: 'SET_NONE'
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE"
}